# This is workflow name
name: Hello

# Runs on a Trigger
on: 
   push:
       branches: [main]

# This is Name of Job
jobs:
  Greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello to Nikhil
        run: echo "Hello Nikhil"
  Bye:     
    runs-on: ubuntu-latest
    needs: Greet
    steps:
      - name: Say Hello to Nikhil
        run: echo "Hello Nikhil"
